### ISSUE TITLE
suspicious dependency on gepetto.blender.exportmotion

### ISSUE THREAD

**Issue by Kevin-Giraud-Esclasse** [humanoid-path-planner/hpp-rbprm-corba#24]
Hello everybody,
I let here this error I had. Just commenting this line worked in my case.

/opt/openrobots/lib/python2.7/site-packages/hpp/corbaserver/rbprm/rbprmfullbody.py in <module>()
     19 from hpp.corbaserver.rbprm import Client as RbprmClient
     20 from hpp.corbaserver.robot import Robot
---> 21 import hpp.gepetto.blender.exportmotion as em
     22 from numpy import array, matrix
     23 from hpp_spline import bezier

ImportError: No module named gepetto.blender.exportmotion

**Comment by stonneau** [comment]
Hey,
can you make a pull request out of it ?
