### ISSUE TITLE
hyq_visual dae could not be opened

### ISSUE THREAD

**Issue by jkw0701** [humanoid-path-planner/hpp-rbprm-corba#33]
Hello, 

I installed HPP in ubuntu 16.04 and ros-kinetic as described :

Follow this instructions : http://humanoid-path-planner.github.io/hpp-doc/download.html (select 'Devellopement" in the list)
 Once this installation is complete, run make rbprm

Then, when launching /hpp-rbprm-corba/scripts/scenarios/demos/darpa_hyq.py,  
the following error is happened : 
Error: gepetto.corbaserver.gepetto.Error(msg='File $ROS_PACKAGE_DIR/hyq-rbprm/meshes/hyq_visual.dae found but could not be opened. Check that a plugin exist.')

I thought this was related to collada-dom or osg-dae, but I already installed those.

How can I solve this? 

Thanks.

**Comment by jmirabel** [comment]
Hello,

what's the content of /opt/openrobots/lib/osgPlugins*/ ?

**Comment by jkw0701** [comment]
There is library osgdb_dae.so in  /opt/openrobots/lib64/osgPlugins-3.2.1/

Thank you.

**Comment by jkw0701** [comment]
I fixed this problem with managing ~/.bashrc.

Thanks.
