### ISSUE TITLE
CORBA transient error when running the server

### ISSUE THREAD

**Issue by pFernbach** [humanoid-path-planner/hpp-rbprm-corba#46]
Issue originally opened in https://github.com/stonneau/hpp-rbprm/issues/22

__________________________________________________________

When I try to run hpp-rbprm-server I got this:
```
ORBA: CORBA::Exception TRANSIENT:IDL:omg.org/CORBA/TRANSIENT:1.0 : failed to narrow the root naming context
CORBA: CORBA::SystemException: failed to narrow the root naming context.
terminate called after throwing an instance of 'hpp::Exception'
  what():  Failed to start corba server.
Aborted (core dumped)
```

I got the same errors when running the other corbaserver

_Originally posted by @teguhSL in https://github.com/stonneau/hpp-rbprm/issues/22#issuecomment-533115099_

__________________________________________________________

Hi @teguhSL 

If you run `nameclt list`, do you have any error ?

_Originally posted by @nim65s in https://github.com/stonneau/hpp-rbprm/issues/22#issuecomment-533117127_

**Comment by teguhSL** [comment]
Running ```nameclt list``` gives me this:
```
Cannot resolve the root context.
Have you set up the configuration file properly?

```

**Comment by nim65s** [comment]
ok, is the `omniNames` process running ?

Either it is not started (and you can start it with `omniNames -start`), or its configuration is not clear (and you can fix that with `export NameService=corbaname::localhost`)

**Comment by jmirabel** [comment]
Did you try https://github.com/Gepetto/gepetto-viewer-corba#corbatransient-when-launching-a-server already ?

**Comment by teguhSL** [comment]
Ok, now by following
```
ok, is the omniNames process running ?

Either it is not started (and you can start it with omniNames -start), or its configuration is not clear (and you can fix that with export NameService=corbaname::localhost)
```
omniNames is running, and I can run hbb-rbprm-server. 

Then I run the following codes from ```darpa_hyq_path.py```,
```
from hpp.corbaserver.rbprm.hyq_abstract import Robot
```

and get these errors:
```
omniORB: (0) 2019-09-19 16:01:07.669351: ERROR! omniORBpy version 4.2 expects stubs version 4.2. Stubs in /opt/openrobots/lib/python2.7/site-packages/hpp_stubs/corbaserver/obstacle_idl.pyc are version 3.0 (rev 0).
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-204577a9b00a> in <module>()
----> 1 from hpp.corbaserver.rbprm.hyq_abstract import Robot

/opt/openrobots/lib/python2.7/site-packages/hpp/corbaserver/__init__.py in <module>()
----> 1 from .client import Client
      2 from .robot import Robot
      3 from .problem_solver import ProblemSolver, newProblem
      4 from .tools import loadServerPlugin, createContext
      5 from .benchmark import Benchmark

/opt/openrobots/lib/python2.7/site-packages/hpp/corbaserver/client.py in <module>()
      6 import CosNaming
      7 
----> 8 import hpp_idl.hpp.corbaserver
      9 
     10 class CorbaError(Exception):

/opt/openrobots/lib/python2.7/site-packages/hpp_idl/hpp/__init__.py in <module>()
      7 
      8 # ** 1. Stub files contributing to this module
----> 9 import hpp_stubs.corbaserver.obstacle_idl
     10 import hpp_stubs.corbaserver.problem_idl
     11 import hpp_stubs.corbaserver.robot_idl

/opt/openrobots/lib/python2.7/site-packages/hpp_stubs/corbaserver/obstacle_idl.py in <module>()
      5 _0_CORBA = CORBA
      6 
----> 7 _omnipy.checkVersion(3,0, __file__)
      8 
      9 # #include "hpp/common.idl"

ImportError: Stubs not compatible with omniORBpy version 4.2.

```

**Comment by nim65s** [comment]
Thanks, I'm starting to understand. Which OS are you using ?

**Comment by teguhSL** [comment]
I'm using Ubuntu 16.04

**Comment by nim65s** [comment]
I think you have `robotpkg-omniorbpy`, and that you should remove it, to use the standard `python-omniorb` package from Ubuntu.

omniORBpy should be on version 3 on 16.04.

**Comment by teguhSL** [comment]
I already uninstall ```robotpkg-omniorbpy```, but I still have the same issue. 

Do you mean to remove also ```robotpkg-omniorb```?
Indeed, I did not have ```robotpkg-omniorb``` after following the installation procedure, so I install it myself by ```sudo apt-get install robotpkg-omniorb```. Otherwise, calling omniNames results in:
```
bash: /opt/openrobots/bin/omniNames: No such file or directory
``` 

although I have ```python-omniorb``` installed (version (3.6-1))

**Comment by nim65s** [comment]
`omniNames` should be in `omniorb-nameserver`: `/usr/bin/omniNames`

**Comment by teguhSL** [comment]
After removing ```robotpkg-omniorb```, apparently I still have two versions of omniNames, in ```/usr/bin``` and ```/usr/local/bin```. The problem persists, so I remove the one in ```/usr/local/bin```. However, it seems that I am still running omniorb version 4. 

I check ```/usr/lib``` and I have the following files:
```
libomniORB4.a
libomniORB4.so
libomniORB4.so.1
libomniORB4.so.1.6
```

How can I downgrade the running omniorbpy from 4.2 to 3.6? I already install 3.6 by ```sudo apt-get install python-omniorb``` and get:

```
python-omniorb is already the newest version (3.6-1).
```
But when I run the rb-prm program I still have the same error saying that my omniorbpy is version 4.2.

**Comment by nim65s** [comment]
Having omniorb-nameserver v4.1 & python-omniorb v3.6 is normal.

But if I start a clean 16.04, with robotpkg-hpp-rbprm-corba, python-omniorb, omniorb-nameserver, I can get the following:
```
In [1]: import _omnipy

In [2]: _omnipy.checkVersion(3,0, "/opt/openrobots/lib/python2.7/site-packages/hpp_stubs/corbaserver/obstacle_idl.py")

```
without error.

Can you try to see what gives `python -c 'import _omnipy; print _omnipy.__file__'` ?

For me, that's `/usr/lib/python2.7/dist-packages/_omnipymodule.so`, which is a correct path for python-omniorb

**Comment by jmirabel** [comment]
You have to reinstall corba packages (hpp-corbaserver, hpp-rbprm-corba...) because the servers and clients must be regenerated.

**Comment by teguhSL** [comment]
Running ```python -c 'import _omnipy; print _omnipy.__file__'``` gives me:
```/usr/lib/python2.7/dist-packages/_omnipymodule.so```
so I remove this file, and then running the above command now gives me the correct location:
```/usr/lib/python2.7/dist-packages/_omnipymodule.so```

After this I uninstall and reinstall hpp packages through robotpkg. Running
```
In [1]: import _omnipy

In [2]: _omnipy.checkVersion(3,0, "/opt/openrobots/lib/python2.7/site-packages/hpp_stubs/corbaserver/obstacle_idl.py")
```
returns without error, so it seems I have the correct version now. 

However, running the codes
```
from hpp.corbaserver.rbprm.hyq_abstract import Robot
```
now gives me new error:

```
omniORB: Assertion failed.  This indicates a bug in the application
using omniORB, or maybe in omniORB itself.
 file: ../../modules/omnipy.cc
 line: 459
 info: omniPy::pyomniORBpoaCache
terminate called after throwing an instance of 'omniORB::fatalException'
Aborted (core dumped)
```

**Comment by nim65s** [comment]
Ok, at this point it might be useful to clean your install and start again…
You can try with `sudo apt purge \*omni\*` and then `sudo apt install omniorb omniorb-nameserver python-omniorb python-omniorb-omg`

**Comment by teguhSL** [comment]
I did what you suggested: purging \*omni\* and \*hpp\*, and then reinstall. But the problem still appears:
```
omniORB: Assertion failed.  This indicates a bug in the application
using omniORB, or maybe in omniORB itself.
 file: ../../modules/omnipy.cc
 line: 459
 info: omniPy::pyomniORBpoaCache
terminate called after throwing an instance of 'omniORB::fatalException'
Aborted (core dumped)


```

**Comment by nim65s** [comment]
If I start a clean 16.04 with robotpkg apt repositories
```
sudo apt install omniorb omniorb-nameserver python-omniorb python-omniorb-omg robotpkg-hpp-rbprm-corba robotpkg-py27-qt4-hpp-gepetto-viewer
```

I can execute `from hpp.corbaserver.rbprm.hyq_abstract import Robot` without errors.

Without being able to reproduce your issue, it's hard to find a fix…

Then maybe you can try to reinstall ubuntu.

**Comment by teguhSL** [comment]
Hi, I have just tried on a freshly installed ubuntu and the first line works, thank you!

Now the problem is with gepetto_gui, when I launch it I got this:
'''
"omniorbserver.so" :  "The shared library was not found." 
Plugin "omniorbserver.so" not loaded: "The shared library was not found." 
'''
I have tried restarting the omniNames but the problem remains

**Comment by jmirabel** [comment]
The file omniorbserver.so should be in /opt/openrobots/lib/gepetto-gui-plugins.
- If it is, then your LD_LIBRARY_PATH likely does not contain /opt/openrobots/lib
- If it is *not*, then you may not have installed it. It should have been installed by the command above. It is part of package robotpkg-py27-qt4-gepetto-viewer-corba

**Comment by teguhSL** [comment]
Thank you @jmirabel , now the example is working!
