### ISSUE TITLE
Parameter missing in Function interpolateConfigs(...) in python

### ISSUE THREAD

**Issue by JasonChmn** [humanoid-path-planner/hpp-rbprm-corba#50]
In function ``interpolateConfigs(...)`` in file : corbaserver/rbprm/rbprmfullbody.py
Need to change :
`` return self.clientRbprm.rbprm.interpolateConfigs(configs, robustnessTreshold, filt, testReachability, quasiStatic)``
To
`` return self.clientRbprm.rbprm.interpolateConfigs(configs, robustnessTreshold, filt, testReachability, quasiStatic, True)``

**Comment by nim65s** [comment]
moved :)

**Comment by pFernbach** [comment]
I added a parameter in the python API : https://github.com/humanoid-path-planner/hpp-rbprm-corba/pull/71

However I put the default value to False, such that it doesn't change the current behavior.
