### ISSUE TITLE
Parent initializer called in loadModel function

### ISSUE THREAD

**Issue by JasonChmn** [humanoid-path-planner/hpp-rbprm-corba#54]
In rbprmbuilder and rbprmfullbody, parent initializer is called in loadModel function.
It may be better to put it back directly in the constructor.

https://github.com/humanoid-path-planner/hpp-rbprm-corba/blob/e3da9658d5736a443835968740abf464b5fe5e0e/src/hpp/corbaserver/rbprm/rbprmbuilder.py#L44-L45
https://github.com/humanoid-path-planner/hpp-rbprm-corba/blob/e3da9658d5736a443835968740abf464b5fe5e0e/src/hpp/corbaserver/rbprm/rbprmfullbody.py#L46-L47

If done that way, we will have to move the client argument from loadModel() to constructor (See client argument : https://github.com/humanoid-path-planner/hpp-rbprm-corba/pull/53)

**Comment by pFernbach** [comment]
Is it solved by https://github.com/humanoid-path-planner/talos-rbprm/pull/10 ?

**Comment by pFernbach** [comment]
Fixed by https://github.com/humanoid-path-planner/hpp-rbprm-corba/pull/73/commits/a6cf76a16799099071edaca1b7aace4ecb4a679f
