### ISSUE TITLE
missing unit tests

### ISSUE THREAD

**Issue by stonneau** [humanoid-path-planner/hpp-rbprm-corba#60]
The following functionalities do not work in the current binary release. They should be tested automatically:

- the rbprmState file includes inexisting python file (com_inequalities.py)

- the method addContact from fullBody takes an extra quaternion as parameter now

- operator () from Path instance fails if extraconfigs are present

The last two issues have already been fixed but are not tested.

**Comment by pFernbach** [comment]
Solved by https://github.com/humanoid-path-planner/hpp-rbprm-corba/pull/62
